Feat/create user authentication
mllrdev-glenn-henares/purchase-order pull request #5
Opened 2021-08-12 08:24 UTC by mllrdev-glenn-henares

2021-08-12 08:41 UTC, cerino-ligutom requested changes

2021-08-12 08:41 UTC, cerino-ligutom commented on public/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorig
Do you even need this? If yes, use a solution that doesn't use a CDN.

2021-08-12 08:41 UTC, cerino-ligutom commented on src/components/Toolbar.vue
> +      <div id="title-bar" >
```suggestion
      <div class="title-bar" >
```

Just some semantics, only use `id` if it's really unique throughout the entire app AND you want to access it in javascript. If the former doesn't apply, opt for using css classes.

2021-08-12 08:41 UTC, cerino-ligutom commented on src/components/Toolbar.vue
> +  props: ['titleText'],
```suggestion
  props: {
    titleText: {
      type: String,
      required: true
    },
  },
```

Always use the full form. See [style guide for prop definitions](https://v3.vuejs.org/style-guide/#prop-definitions-essential).

2021-08-12 08:41 UTC, cerino-ligutom commented on src/core/enums/route-names.enum.ts
> +export enum RouteNames {
```suggestion
export enum RouteName {
```

enums should be in singular form unless the values are BIT

2021-08-12 08:41 UTC, cerino-ligutom commented on src/core/interfaces/user.ts
> +}
What benefits do you see in separating these interfaces? I believe they can be merged, no?

2021-08-12 08:41 UTC, cerino-ligutom commented on src/core/models/api-urls.ts
> +export default { apiUrl, apiLoginUrl, apiSignupUrl}
This isn't a model (based on directory path and content of this file) so this does not belong here.

2021-08-12 08:41 UTC, cerino-ligutom commented on src/core/services/api.service.ts
> +}
Wrong api service.

2021-08-12 08:41 UTC, cerino-ligutom commented on src/pages/Register.vue
> +    return { router };
Isn't this unnecessary?

2021-08-12 08:41 UTC, cerino-ligutom commented on src/pages/Register.vue
> +  width: 5in;
Don't use the `in` unit for styling an app.  Usually that unit is used when you're trying to print a web page and have constraints for the paper size.

2021-08-20 05:23 UTC, mllrdev-carlo-medel approved these changes

2021-08-23 04:40 UTC, mllrdev-carlo-medel approved these changes

2021-08-23 04:50 UTC, merged